import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalHeader from "@/components/ConditionalHeader";
import Footer from "@/components/Footer";
import Providers from "@/components/Providers";
import AuthProvider from "@/components/AuthProvider";
import Header from "@/components/Header";
import { LanguageProvider } from "@/contexts/LanguageContext";
import { translations } from "@/locales";

// Temporarily disabled due to Google Fonts network restrictions in build environment
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <Providers>
          <AuthProvider>
            <LanguageProvider translations={translations}>
              {/* <ConditionalHeader /> */}
              <Header />
              {children}
              <Footer />
            </LanguageProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
